# Generated by Django 4.2.22 on 2025-06-06 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('HIIT', 'HIIT')], max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('available_slots', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Fitness Classes',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings_app.fitnessclass')),
            ],
            options={
                'ordering': ['-booking_time'],
                'unique_together': {('fitness_class', 'client_email')},
            },
        ),
    ]
