# Generated by Django 4.2.22 on 2025-06-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fitnessclass',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings_app.fitnessclass'),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
